service: star-wars-api
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  profiles:
    dev: personalAccount

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile: ${self:custom.profiles.${self:provider.stage}}

functions:
  listPeople:
    handler: src/handlers/people.list
    events:
      - httpApi:
          path: /api/people
          method: get
  createPeople:
    handler: src/handlers/people.create
    events:
      - httpApi:
          path: /api/people
          method: post
