service: star-wars-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: src/handlers/get-planets.hello
    events:
      - httpApi:
          path: /
          method: get
